# Generated by Django 5.2.1 on 2025-05-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="like_count",
            new_name="likes",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
