# Generated by Django 5.2.1 on 2025-05-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_videofile_video"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="videofile",
            unique_together={("video", "quantity")},
        ),
    ]
