# Generated by Django 5.2.1 on 2025-05-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_rename_owner_like_user_alter_like_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="like_count",
            new_name="likes_count",
        ),
    ]
