# Generated by Django 5.2.1 on 2025-05-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_rename_like_count_video_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="videos.video",
            ),
        ),
    ]
