# Generated by Django 5.2.1 on 2025-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_rename_likes_count_video_total_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
