# Generated by Django 5.2.1 on 2025-07-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_alter_videofile_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videofile",
            old_name="quantity",
            new_name="quality",
        ),
        migrations.AlterUniqueTogether(
            name="videofile",
            unique_together={("video", "quality")},
        ),
    ]
