volumes:
  django-postgres:


services:
  postgres:
    image: postgres:17
    container_name: django-default-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: "${POSTGRES_DEFAULT_DB}"
      POSTGRES_USER: "${POSTGRES_DEFAULT_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_DEFAULT_PASSWORD}"
      POSTGRES_PORT: "5432"
    ports:
      - "${POSTGRES_DEFAULT_PORT}:5432"
    volumes:
      - django-postgres:/var/lib/postgresql/data
